const copy = {};

copy[1] = `
<p><strong>Why?</strong> Even the smallest events can produce impacts reaching far beyond their immediate time and place. Whether through their direct operations or investments, firms of all sizes can pose significant risks to ecology and humans alike. It is important to consider partnerships with organizations and sponsors that have positive reputations for consideration and mitigation of the potential environmental, social, and economic impacts of their operations.</p>
<p><strong>How?</strong> Recognizing the importance of Corporate Social Responsibility, many organizations and firms publish their CSR mandates or strategies online – This can be a great way to find out what your potential partners&#39; approach to sustainability is. We also recommend considering certified <a href="https://www.bcorporation.net/what-are-b-corps" target="_blank">B-Corp</a>, <a href="http://fairtrade.ca" target="_blank">Fair Trade</a>, and <a href="https://www.onepercentfortheplanet.org/about-us" target="_blank">1% For The Planet</a> organizations, as well as those ranked within <a href="http://www.corporateknights.com/reports/2017-global-100/" target="_blank">Corporate Knights&#39; 2017 global 100</a> socially responsible firms list.</p>
`;

copy[2] = `
<p><strong>Why?</strong> In order to host events that are as inclusive, equitable, and accessible as possible, it is important to include a diversity of perspectives in your planning and implementation processes. Diversity here can be understood in terms of gender, sexual, ethnic, and religious identification, immigration history, mental and physical ability, and more. Diversity can also pertain to the inclusion of students, staff, and faculty across all of McGill&#39;s departments and faculties.</p>
<p><strong>How?</strong> It is important not to consider diversification efforts in terms of labels or quotas, but rather in terms of process. When assembling your team members at any level of involvement, we recommend you consider which communities may be systematically underrepresented or marginalized – these voices can often be those with the most to contribute to your event. More information on the inclusion of diverse voices can be found on at the website of <a href="http://ssmu.mcgill.ca/ua/equity/" target="_blank">SSMU equity</a>. For additional info, consider contacting McGill&#39;s <a href="https://www.mcgill.ca/equity_diversity/" target="_blank">Social Equity and Diversity Education Office</a>.</p>
`;

copy[3] = `
<p><strong>Why?</strong> Nearly every aspect of your event can contribute to the emission of carbon dioxide into our shared atmosphere (travel emissions, food and energy production, etc). Carbon offsets are voluntary payments to third-party organizations to compensate for harmful greenhouse gas emissions elsewhere. In order to mitigate the effects of these emissions, carbon offsets can be used to fund developments like carbon sequestration (e.g. tree-planting) and renewable energy infrastructure. For more information about sustainable travel, including aspects related to carbon emissions, please read the <a href="https://mcgill.ca/sustainability/files/sustainability/sustainable_travel_and_mobility_guide_1.pdf" target ="_blank">Sustainable Travel and Mobility Guide</a>, prepared by the Office of Sustainability.</p>
<p><strong>How?</strong> When it comes to carbon offsetting, quality matters. For the purposes of our certification program, we require <a href="https://www.goldstandard.org/our-standard/about-our-standard" target="_blank">Gold Standard</a> certified offsets. Some platforms we recommend for offsetting your event include <a href="http://planetair.ca/en/v2/comprendre.sn" target="_blank">Planetair</a>, <a href="https://treecanada.ca/en/" target="_blank">TreeCanada</a>, and <a href="http://www.carbonneutral.com/about" target="_blank">Carbon Neutral</a>. Though not required, some excellent carbon footprint calculators include <a href="http://www.carbonfootprint.com/calculator.aspx" target="_blank">Carbon Footprint</a> and McGill&#39;s very own <a href="http://moostrax.ca" target="_blank">MOOStrax</a>.</p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">SPF Tiny Stream.</a></p>
`;

copy[4] = `
<p><strong>Why?</strong> Different individuals and communities face various barriers to participation. In order to make your event as inclusive as possible, it is important to inform your potential attendees of the accessibility accommodations and restraints of both your venue and programming. This information may pertain to matters of physical accessibility such as ramp and lifts, or to other matters such as the availability of gender-neutral restrooms.</p>
<p><strong>How?</strong> We recommend sharing this information through whichever channels you intend to communicate with your target audience or attendees. This could mean including this information on your website, on a Facebook event, group, or post, or sending an email. For an example of this kind of publicity, click <a href="https://drive.google.com/open?id=0B76le4GH2RXlTFdsQlZ6cVN2elE" target="_blank"><strong>here</strong></a>.</p>
`;

copy[5] = `
<p><strong>Why?</strong> In order to make your event as inclusive as possible, it is important that it be scheduled during times and dates that will not exclude those celebrating religious or cultural holidays from attending. It is also important to consider other factors such as academic/work schedules in attempting to offer your event at a time that accommodates as many individuals and communities as possible.</p>
<p><strong>How?</strong> When scheduling your event, consult with McGill&#39;s <a href="https://www.mcgill.ca/hr/employee-relations/statutory-holidays-summer-fridays" target="_blank">statutory holiday</a> and <a href="https://www.mcgill.ca/importantdates/key-dates" target="_blank">key academic date</a> lists.</p>
`;

copy[6] = `
<p><strong>Why?</strong> Certain individuals and communities may be systematically disadvantaged from attending your event due to various financial constraints. In order to host events that are financially accessible to all, it is important to offer pricing models that offer flexibility.</p>
<p><strong>How?</strong> A commonly practiced example of flexible pricing models is the offering of student and senior discounts. Other models include pricing your event by donation, and of course an ideal model is offering free admission for certain/all attendees!</p>
<p>To further ensure the financial accessibility of your event, you can consider other tips listed in <a href="https://drive.google.com/file/d/1v7DlDSdo5lXFurDb9k3YyNJWwA5xfi6v/view" target="_blank">this resource</a>.</p>
`;

copy[7] = `
<p><strong>Why?</strong> Different individuals and communities face various barriers to participation. In order to make your event as inclusive as possible, it is important that considerations be made of attendees' varying needs. Universal Design is the design and composition of an environment so that it can be accessed, understood and used to the greatest extent possible by all people regardless of their age, size, ability, etc.</p>
<p><strong>How?</strong>
The three main <a href="https://mcgill.ca/osd/faculty-staff/resources/udl-documents" target="_blank">Universal Design Principles</a> are representation, action and expression, and engagement. These are important to consider in every type of event (workshops, speakers, panels, networking, etc) and particularly for events where considerable amounts of information is shared. Here are a few things you can implement in your events: <br>
<ul>
<li>Have multiple means of representing the information you display. Try to verbally communicate the information on the PowerPoint and vice-versa to help people with hearing and visual impairments. i.e. indicate visually and verbally where the washrooms are in the building, explain verbally what the content of an image on the PowerPoint is.</li>
<li>Structure your PowerPoint presentations such that people know what the structure of the presentation will be and can find landmarks throughout the presentation. Presentation outlines, headings, and consistent layout can assist in doing this. Concept maps can help for more specific concepts within the presentation.</li>
<li>Ensure that the presentations in your event are easily readable by as many people as possible. Ensure that you have good contrast between text and background, and use text colors that are easily distinguished by all (i.e. choose green and purple over green and red as they offer better contrast for people with difficulty differentiating colors). Also provide short image captions, avoid glossy colors, and emphasize key points using both colors and physical means (i.e. use bold or underlined text and bigger fonts). Use sans serif fonts instead of serif (e.g. Arial or Verdana instead of Times New Roman).</li>
<li>If possible, provide a copy of the content presented in advance so attendees can follow the presentation on a printed or downloaded version. If you do, ensure that all your documents can be easily read by a screen reader; <a href="https://support.office.com/en-us/article/use-the-accessibility-checker-on-your-windows-desktop-to-find-accessibility-issues-a16f6de0-2f39-4a2b-8bd8-5ad801426c7f" target="_blank">Microsoft accessibility checker</a> feature can be a useful tool to help you.</li>
<li>Give people several means of engaging with the event: answering quizzes, collaborating in a workshop through cloud servers, allowing people to ask questions during or after the event.</li>
<li>Allow for multiple means of expression: offer the opportunity to ask questions at a microphone and on online platforms (Twitter feed and <a href="https://www.sli.do/" target="_blank">Slido</a>), allow presenters to attend in person or through video-conferencing platforms.</li>
</ul></p>
`;

copy[8] = `
<p><strong>Why?</strong> The success of an event often depends on the efforts of many individuals. It is important that event planners compensate and accommodate these individuals.</p>
<p><strong>How?</strong> Legally, any paid employee in Quebec is entitled to fair practice under local <a href="http://legisquebec.gouv.qc.ca/en/showdoc/cs/C-27" target="_blank">labour code</a>. For volunteers, some examples of fair practice would include the provision of space and time for fair breaks, or alternative compensation such as food or clear learning objectives and opportunities.</p>
`;

copy[9] = `
<p><strong>Why?</strong> Your existing event team may not have been structured with sustainability as a priority, and that&#39;s okay! Recruiting team members with the specific mandate of implementing sustainability is an effective way of ensuring that your sustainability objectives are met. These actions could include anything on this page, such as reducing waste by collecting materials and ensuring proper receptacle signage, circulating feedback surveys, or helping direct individuals towards ramps, lifts, or appropriate restrooms.</p>
<p><strong>How?</strong> As sustainability relates to essentially all aspects of event-planning, we recommend you make an effort to recruit these personnel as early as possible. Consider consulting <a href="https://www.mcgill.ca/studentleaders/handbook/communications/listservs/campus-listservs" target="_blank">this</a> list in order to publicize your recruitment efforts.</p>
`;

copy[10] = `
<p><strong>Why?</strong> Setting a sustainability vision for your event provides a great opportunity to set achievable goals while also promoting a conversation about sustainable event planning amongst your planning team.</p>
<p><strong>How?</strong> After determining an overall sustainability vision for your event, ensure that you set more specific sustainability objectives and targets for your event. Objectives should be achievable goals while targets can be used as metrics to ensure you meet those goals.</p>
`;

copy[11] = `
<p><strong>Why?</strong> Individuals with varying levels of physical ability could potentially be prevented from participating in your event if an accessible venue is not offered. <strong> </strong> It is important that your event be free of as many physical barriers as possible. Physical barriers of access can include: inaccessible elevations (lack of ramps, lifts, etc.), lack of accessible restrooms, inappropriate lighting, and more.</p>
<p><strong>How?</strong> Thanks to the McGill Office for Students with Disabilities, a number of <a href="http://www.mcgill.ca/osd/access" target="_blank">resources</a> are available that can help you plan your event to be physically accessible to all. In addition, if you’d like to see the accessibility details (entrances, washrooms, barriers) for each building on McGill’s campuses, click <a href="http://www.mcgill.ca/osd/files/osd/accessibilityguide_downtowncampusupdate.pdf" target="_blank">here</a> for the Downtown Campus and <a href="http://www.mcgill.ca/osd/files/osd/accessibilityguide_macdonaldcampus.pdf" target="_blank">here</a>.</p>
<p>The Social Equity and Diversity Education Office lists a few tips for reducing physical barriers in <a href="https://drive.google.com/file/d/1v7DlDSdo5lXFurDb9k3YyNJWwA5xfi6v/view" target="_blank">this resource</a> on inclusive event planning.</p>
`;

copy[12] = `
<p><strong>Why?</strong> In order to provide an event that all are able to participate in, it is important that your event be accessible for those who depend on using public transportation to get there. We consider a venue to be easily accessible via public transportation to be one that is less than a 5 minute walk from the nearest transport drop-off point. The <a href="https://mcgill.ca/sustainability/files/sustainability/sustainable_travel_and_mobility_guide_1.pdf" target ="_blank">Sustainable Travel and Mobility Guide</a>, prepared by the Office of Sustainability, explains why it is important to travel via public transit and some other modes of sustainable transportation.</p>
<p><strong>How?</strong> The public transit system in Montreal (STM) offers a number of public transport options that attendees can make use of to get to your event. For more information on these options and their drop-off points, visit the STM&#39;s <a href="http://www.stm.info/en" target="_blank">website</a>.</p>

`;

copy[13] = `
<p><strong>Why?</strong> The energy consumed by the building your event is hosted in can result in significant emissions of greenhouse gases. The effects of this emission can be mitigated by hosting your event in a building that has been certified as sustainably designed.</p>
<p><strong>How?</strong> While a number of sustainable design certifications exist, it is important to note that there are certifications that look exclusively at the sustainability of the construction of the building and the forecasted environmental impact of its operations, while there are others that track the ongoing environmental impact of the building in near real-time. Some certifications we recommend include: <a href="http://www.cagbc.org/CAGBC/Programs/LEED/LEED_Canada_Rating_System/LEED_Canada_Rating_System.aspx" target="_blank">LEED</a>, <a href="http://bomacanada.ca/bomabest/" target="_blank">BOMA-Best</a>, <a href="http://www.breeam.com" target="_blank">BREEAM</a>, and <a href="https://standard.wellcertified.com/well-certification" target="_blank">WELL</a>. At McGill, the <a href="https://www.mcgill.ca/lifesciencescomplex/" target="_blank">Life Sciences Complex</a> has been LEED certified, and the Armstrong, Brown, and La Citadelle buildings are in the process of getting their LEED certifications. <a href="https://docs.google.com/document/d/11aEGXAKBAT0G98TLNpIyLKxDHMsaSnnN9DV4JAi1p4s/edit?usp=sharing" target="_blank">Here</a> is a list of some sustainably-designed buildings at McGill and in Montreal.</p>
`;

copy[14] = `
<p><strong>Why?</strong> For the McGill community, holding your event at a McGill location allows for easier access for most your attendees, while also promoting the use of McGill spaces and resources.</p>
<p><strong>How?</strong> Click <a href="https://www.mcgill.ca/eventsbookings/events-bookings-mcgill" target="_blank">here</a> in order to browse locations on campus where you can host an event. In addition, you can contact faculty associations to book venues in their spaces ( <a href="http://ssmu.mcgill.ca/events/room-booking-categories/" target="_blank">SSMU</a>, <a href="https://ausmcgill.com/services/bookings/rooms/" target="_blank">AUS</a>, <a href="http://www.mus.mcgill.ca/bookings/" target="_blank">MUS</a>, <a href="http://sus.mcgill.ca/resources/table-booking/" target="_blank">SUS</a>, <a href="https://www.mcgill.ca/engineering/students/undergraduate/student-life/room-requests" target="_blank">EUS</a>, <a href="http://mcss.mcgill.ca/society/services/rental" target="_blank">MCSS</a>)</p>
`;

copy[15] = `
<p><strong>Why?</strong> A common barrier for people with disabilities is transport to and from your event, and unfortunately Montreal&#39;s current public transit infrastructure does not make that any easier. In order to make your event accessible for all attendees, you should be aware of anybody attending your event who may require assistance in getting to and from the event, and then be aware of the appropriate tools to do so.</p>
<p><strong>How?</strong> The public transit system in Montreal (STM) does offer accessible transport that can be ordered to pick up event attendees, however the process to do so is quite complex. The first step is to ensure you find out whether any event attendees will require special assistance. This can be done by simply including a short <a href="https://docs.google.com/document/d/1oFPbL7qsV1_8dMqbNWg9zjeafOvmbO7yZzBCznPSfvs/edit?usp=sharing" target="_blank">blurb</a> in your email callout or your social media posts, at the same time that you would ask for things like dietary restrictions. Once you are in communication with any event-attendees who will require accessible transport, you can inquire whether they have an OPUS paratransit ID card – this card is required to order accessible transport. In the event that they don&#39;t have one, they can fill out the application form at <a href="http://www.stm.info/en/para" target="_blank">this</a> website. Unfortunately, most requests take up to 45 days to be processed, and if your event will occur sooner than that, then STM&#39;s transport system will not be of use. If this is the case, you can arrange to provide an accessible taxi, simply make sure to book this well in advance. In the event that the event attendee does have an OPUS paratransit card, then you can simply call 514-280-8211 or order online <a href="https://www.stm.info/en/paratransit/using-paratransit/reserving-changing-and-cancelling/reserving-trips" target="_blank">here</a> to pre-order the transport. Make sure to do this at least 48 hours in advance, and ensure that you leave some buffer time as the system is notorious for being late.</p>
`;

copy[16] = `
<p><strong>Why?</strong> In order to accommodate accessibility issues and avoid unnecessary emissions associated with long-distance travel, events can be recorded or summarized for later distribution. For more information about sustainable travel, including aspects related to carbon emissions, please read the <a href="https://mcgill.ca/sustainability/files/sustainability/sustainable_travel_and_mobility_guide_1.pdf" target ="_blank">Sustainable Travel and Mobility Guide</a>, prepared by the Office of Sustainability.</p>
<p><strong>How?</strong> Various methods of recording or otherwise providing an event recap are available. For example, if you&#39;re looking for photography or videography services, the McGill student club <a href="https://www.photofund.ca" target="_blank">PhotoFund</a> currently offers those services for reduced rates and donates all proceeds to charity. Additional options include <a href="https://live.fb.com/about/" target="_blank">Facebook Live</a>, recording video for later uploading to Youtube, and posting written summaries or minutes online.</p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">SPF Tiny Stream</a>.</p>
`;

copy[17] = `
<p><strong>Why?</strong> In order to accommodate accessibility issues and avoid unnecessary emissions associated with long-distance travel, individuals may be provided the option to participate in your event through telecommunication. For more information about sustainable travel, including aspects related to carbon emissions, please read the <a href="https://mcgill.ca/sustainability/files/sustainability/sustainable_travel_and_mobility_guide_1.pdf" target ="_blank">Sustainable Travel and Mobility Guide</a>, prepared by the Office of Sustainability.</p>
<p><strong>How?</strong> Many free software platforms exist, such as <a href="https://appear.in" target="_blank">Appear.In</a>, <a href="https://www.skype.com/en/" target="_blank">Skype</a>, and Apple&#39;s FaceTime that allow participation from anywhere with an internet connection.</p>
`;

copy[18] = `
<p><strong>Why?</strong> A land acknowledgement is a formal statement that recognizes the unique and enduring relationship that exists between Indigenous Peoples and their traditional territories. A connection to the land is inextricably linked to Indigenous identity. Historically, the cultural protocol of acknowledging traditional territory symbolizes the importance of place and identity for Indigenous peoples. Within many Indigenous communities, protocol requires that individuals situate themselves, and their relationships to the people and the land. For many Indigenous peoples in Canada, and increasingly in broader Canadian society, traditional territory acknowledgements are an important cultural protocol practiced at ceremonial events as a way to acknowledge and honour Indigenous peoples&#39; connections to their ancestral lands. To recognize the land is an expression of gratitude and appreciation to those whose territory you reside on, and a way of honouring the Indigenous people who have been living and working on the land from time immemorial. It is important to understand the long standing history that has brought you to reside on the land, and to seek to understand your place within that history.</p>
<p><strong>How?</strong> An example of a land acknowledgement being made at an event held on the McGill campus could be: <em>&quot;We would like to acknowledge that McGill University is located on land which has long served as a site of meeting and exchange amongst Indigenous peoples, including the Haudenosaunee and Anishinaabeg nations. McGill honours, recognizes and respects these nations as the traditional stewards of the lands and waters on which we meet.&quot;</em> <i>(La version français suivra)</i> It is important to note, however, that land acknowledgment should be about more than protocol and rhetoric. As such, we encourage you to look beyond these simple words in order to better understand this important matter.</p>
<p><i>Nous voudrions souligner que l’université McGill est située sur un territoire qui a longtemps servi comme site de rencontre et d’échange entre les personnes autochtones, dont les nations Haudenosaunee et Anishinaabeg. McGill honore, reconnait, et respecte ces nations comme étant les gardiens des terres et eaux sur lesquelles nous nous rencontrons aujourd’hui.</i></p>
<p>The following links will provide a pronunciation guide and/or further information about <a href="https://www.youtube.com/watch?v=ZSXL33JiKLY" target="_blank">Haudenosaunee</a> and <a href="https://ojibwe.lib.umn.edu/main-entry/anishinaabe-na" target = "_blank">Anishinaabeg</a>.</p>
`;

copy[19] = `
<p><strong>Why?</strong> In order to host events that are as inclusive, equitable, and accessible as possible, it is important to include a diversity of perspectives in your event programming (speakers, facilitators, etc.). Diversity here can be understood in terms of gender, sexual, ethnic, and religious identification, immigration history, mental and physical ability, and more. Diversity can also pertain to the inclusion of students, staff, and faculty across all of McGill&#39;s departments and faculties.</p>
<p><strong>How?</strong> It is important not to consider diversification efforts in terms of labels or quotas, but rather in terms of process. When recruiting personnel at any level of your programming, we recommend you consider which communities may be systematically underrepresented or marginalized – these voices can often be those with the most to contribute to your event. More information on the inclusion of diverse voices can be found on at the website of <a href="http://ssmu.mcgill.ca/ua/equity/" target="_blank">SSMU equity</a>. For additional info, consider contacting McGill&#39;s <a href="https://www.mcgill.ca/equity_diversity/" target="_blank">Social Equity and Diversity Education Office</a>.</p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">SPF Tiny Stream</a>.</p>
`;

copy[20] = `
<p><strong>Why?</strong> Event attendees come from a wide variety of backgrounds and lived-experiences. In order to provide everyone an equally interactive and engaging learning space – one where participants and facilitators can address topics openly and honestly – it is important to provide structures and opportunities for safe self-expression.</p>
<p><strong>How?</strong> If possible, we recommend offering the opportunity to state <a href="http://lbgtrc.msu.edu/wp-content/uploads/2010/08/PGP-flyer.pdf" target="_blank">gender pronouns</a> during event registration. Otherwise, this practice can take place at the beginning of any small-group discussion – This can easily be integrated into any introductory/ice-breaking activities.</p>
<strong>Informational video coming soon.</strong>
`;

copy[21] = `
<p><strong>Why?</strong> In order to host events that are as inclusive, equitable, and accessible as possible, it is important to promote your event among a diversity of audiences. Diversity here can be understood in terms of gender, sexual, ethnic, and religious identification, immigration history, mental and physical ability, and more. Diversity can also pertain to the inclusion of students, staff, and faculty across all of McGill&#39;s departments and faculties.</p>
<p><strong>How?</strong> It is important not to consider diversification efforts in terms of labels or quotas, but rather in terms of process. When when promoting your event, we recommend you consider which communities may be systematically underrepresented or marginalized – these voices can often be those with the most to gain from or contribute to your event. More information on the inclusion of diverse voices can be found on at the website of <a href="http://ssmu.mcgill.ca/ua/equity/" target="_blank">SSMU equity</a>. For additional info, consider contacting McGill&#39;s <a href="https://www.mcgill.ca/equity_diversity/" target="_blank">Social Equity and Diversity Education Office</a>.</p>
<p>Reaching out to McGill groups and other community organizations can help you encourage attendance among diverse and marginalised groups. Links to various McGill groups, NGO&#39;s, and community organizations can be found <a href="http://www.mcgill.ca/equity_diversity/staff-and-faculty/find-group-or-resource" target="_blank">here</a>.</p>
`;

copy[22] = `
<p><strong>Why?</strong> It is important to provide a comfortable environment for your attendees, and part of this is ensuring that everybody has access to a restroom that meets their needs, regardless of gender identity. Offering gender-neutral and parent-friendly restrooms will help to encourage participation and engagement by making individuals feel more comfortable in the space, as well as have attendees who might not have otherwise come. Our definition of a gender neutral restroom is one that &quot;is a single-person facility which is not labelled male or female but rather is available to anyone, no matter what their gender identity or biological sex&quot;. Parent-friendly restrooms are also important to ensuring that those with children are able to attend your events.</p>
<p><strong>How?</strong> While not all buildings at McGill have gender-neutral restrooms yet, there are still a number that are available. You can find a list generated by the <a href="https://www.mcgill.ca/equity_diversity/" target="_blank">Social Equity and Diversity Education</a> office (SEDE) of all gender-neutral restrooms <a href="https://www.mcgill.ca/equity_diversity/special-projects/gender-neutral-washrooms" target="_blank">here</a>, as well as a list of all buildings without any gender-neutral restrooms at all. For a more detailed list of single stall restrooms that can act as gender neutral with the proper signage, click <a href="http://www.mcgill.ca/equity_diversity/students/equity-projects-mcgill/gender-inclusive-washrooms/locations" target="_blank">here</a>. Keep in mind that single stall restrooms can also be used in place of a gender-neutral restroom. The Post Graduate Students' Society has developed a <a href="https://www.google.com/maps/d/viewer?mid=1ZuPLllVxiYTvpbqWMwbOlw4xMF0&ll" target="_blank">map</a> of on-campus family-friendly locations, including washrooms with changing tables. It is important to communicate that gender-neutral and parent-friendly restrooms are available – as well as their location – before the event. In the case that there are none, communicate the closest one, or that there is a lack thereof.</p>
`;

copy[23] = `
<p><strong>Why?</strong> In order to ensure that your event is accessible to all attendees, all electronic documents that you provide must be in an accessible format. This ensures that event attendees who are visually impaired are able to navigate electronic documents with the same level of independence and privacy as anyone else.</p>
<p><strong>How?</strong> There are a number of steps you can take to ensure that your electronic documents or presentations are more accessible for the visually impaired, including using larger and easier to read fonts and ensuring there is contrast between colour use. However, in order to create documents that are accessible for all users, you must create them so that they can be read by a screen reader. While this can be a relatively time intensive process, if your event is distributing a large amount of electronic documents before, during, or after the event, it will be will worth the effort to ensure accessibility for all. In order to learn how to create documents in an accessible format, click <a href="https://equity.mcmaster.ca/documents/creating-accessible-electronic-materials.pdf" target="_blank">here</a>.</p>
`;

copy[24] = `
<p><strong>Why?</strong> In order to host events that are as inclusive, equitable, and accessible as possible, it is important to ensure that anybody who will be working with your event attendees is trained to interact with diverse communities. This training can ensure that conversations and spaces can provide a comfortable dynamic for exchanges between different perspectives and experiences. Diversity here can be understood in terms of gender, sexual, ethnic, and religious identification, immigration history, mental and physical ability, and more. Diversity can also pertain to the inclusion of students, staff, and faculty across all of McGill&#39;s departments and faculties.</p>
<p><strong>How?</strong> Several organizations offer trainings for moderators and presenters to learn about interacting with diverse communities. Within McGill, the <a href="https://www.mcgill.ca/equity_diversity/" target="_blank">Social Equity and Diversity Education</a> office (SEDE) offers a &quot;Safer Spaces&quot; training multiple times a semester – for schedules and topics, click <a href="https://www.mcgill.ca/equity_diversity/staff-and-faculty/training-and-events/training/safer-spaces-workshops" target="_blank">here</a>. If those times don&#39;t work for you, we also recommend the <a href="http://coco-net.org" target="_blank">Centre for Community Organizations</a> (COCo), however these trainings are generally tailored for community organizations and come at a price. Check their website to see if trainings are scheduled that may work for you. If there are no dates that work with your event, you can also provide your event presenters and facilitators with the information from pages 11 and 13 in <a href="https://drive.google.com/file/d/0B-_V9eVQqZWmcXdwX2s5NWlIV3c/view?usp=sharing" target="_blank">this</a> document.</p>
`;

copy[25] = `
<p><strong>Why?</strong> It&#39;s important for both for attendees and volunteers to be provided breaks during long events in order to rest and refocus.</p>
<p><strong>How?</strong> We recommend that if your event is longer than 3 hours that there be at least a 10 minute break placed in the middle of the event.</p>
`;

copy[26] = `
<p><strong>Why?</strong> Supporting local businesses is not only environmentally sustainable as it generally reduces shipping distances, but it is also economically sustainable, as you ensure that those within your community are financially supported.</p>
<p><strong>How?</strong> A good first step is to use McGill Internal Services (e.g. Printing, Food and Dining/Faculty Club, Special Events, Bookstore) before looking elsewhere. If McGill doesn&#39;t provide the good or service that you&#39;re looking for, expand your search geographically by looking within Montreal, then Quebec, then Canada, before looking to international companies. When working with local suppliers, it is often possible to procure in-kind support, which is an effective way to improve your attendees&#39; experiences.</p>
`;

copy[27] = `
<p><strong>Why?</strong> Even the smallest events can produce impacts reaching far beyond their immediate time and place. It is important to consider purchasing from suppliers that have positive reputations for consideration and mitigation of the potential environmental, social, and economic impacts operations of their operations.</p>
<p><strong>How?</strong> Firstly, any supplier that has been approved by McGill (and can thus be found on the <a href="https://www.mcgill.ca/procurement/mmp" target="_blank">McGill MarketPlace</a>) must be compliant with the university&#39;s Supplier Code of Conduct, which includes clauses related to sustainability. In addition, recognizing the importance of Corporate Social Responsibility, many organizations and firms publish their CSR mandates or strategies online – This can be a great way to find out what your potential partners&#39; approach to sustainability is. We also recommend considering certified <a href="https://www.bcorporation.net/what-are-b-corps" target="_blank">B-Corp</a>, <a href="http://fairtrade.ca" target="_blank">Fair Trade</a>, and <a href="https://www.onepercentfortheplanet.org/about-us" target="_blank">1% For The Planet</a> organizations, as well as those ranked within <a href="http://www.corporateknights.com/reports/2017-global-100/" target="_blank">Corporate Knights&#39; 2017 global 100</a> socially responsible firms list.</p>
`;

copy[28] = `
<p><strong>Why?</strong> Social economy initiatives include non-profit organizations, cooperatives, social enterprises, and charities – which include a component of social good in their mission. By purchasing goods or services from these initiatives, your event can help support and empower the important community endeavours that these initiatives work on.</p>
<p><strong>How?</strong> This is very dependent on the specific goods and/or services that your event requires, but you&#39;ll find that with simply a little extra thought there are plenty of options. Start your search by asking if there are any McGill based clubs or organizations that already offer the good or service that you&#39;re looking for, and then broaden your search to the greater Montreal community. When working with local suppliers, it is often possible to procure in-kind support, which is an effective way to improve your attendees&#39; experiences. For a more comprehensive list of social economy initiatives that events at McGill have worked with in the past, click <a href="https://docs.google.com/document/d/1HamZ9FQayso1ZbLX2fW_u5HOyl9KdFQBR3ZrcPc_eXQ/edit?usp=sharing" target="_blank">here</a>. To find Quebec-based coops, click <a href="https://www.economie.gouv.qc.ca/objectifs/informer/cooperatives/page/repertoires-9757/?%20tx_igaffichagepages_pi1%5Bmode%5D=single&amp;tx_igaffichagepages_pi1%5BbackPid%5D=68&amp;tx_igaff%20ichagepages_pi1%5BcurrentCat%5D" target="_blank">here</a> – For Quebec-based SEI&#39;s, click <a href="http://economiesocialequebec.ca/" target="_blank">here</a> or <a href="http://collectif.qc.ca/formation" target="_blank">here</a></p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">SPF Tiny Stream</a>.</p>
`;
copy[29] = `
<p><strong>Why?</strong> According to University policy, if an event is using McGill operating funds, then it must use a pre-approved McGill catering service, with a few exceptions.</p>
<p><strong>How?</strong> There are two exceptions to this rule: firstly, if you are a student group planning this event using money from your own fund, and secondly, if you are purchasing simple foods as opposed to prepared foods or meals. For example, if you are simply purchasing cheese and crackers for an event, this rule does not apply, but if you are providing pre-made sandwiches for your event attendees, then it does. For more information, and to find out if your event requires this, click <a href="https://www.mcgill.ca/procurement/files/procurement/catering_services_guidelines_final.pdf" target="_blank">here</a>.</p>
`;

copy[30] = `
<p><strong>Why?</strong> Providing vegetarian and vegan options at your event is not only environmentally sustainable as it helps reduce carbon emissions associated with meat production, but it is also socially sustainable as it makes your menu more accommodating to people who chose not to eat meat or animal products for personal and/or religious reasons.</p>
<p><strong>How?</strong> Generally there are plenty of vegetarian and vegan options from restaurants, shops, and caterers, it&#39;s simply a matter of choosing these options for your event. If you would like to take your event menu a step further, we recommend contacting <a href="https://santropolroulant.org/en/activities-and-services/catering/" target="_blank">Santropol Roulant</a> for their catering services, as they offer plenty of locally-grown vegetarian options. In addition, <a href="https://auxvivres.com/en/" target="_blank">Aux Vivres</a> and <a href="http://thegreenpanther.com" target="_blank">La Panthère Verte</a> are able to offer an all vegetarian or vegan menu for your event.</p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">SPF Tiny Stream</a>.</p>
`;

copy[31] = `
<p><strong>Why?</strong> It is important to provide a comfortable environment for your attendees, and part of this is ensuring that everyone's dietary restrictions are accommodated for. By tending to your attendees’ dietary needs, you help make the event more inclusive and accessible.</p>
<p><strong>How?</strong> Before you purchase any food for your event, ensure that you have communicated with any event attendees to see if anyone has dietary restrictions. This can be done in several ways, including in a registration form for your event, in an email directly to event attendees, or simply by providing contact information through email or social media for event attendees to reach out to in the case that they have a dietary restriction. Obviously, you should do your best to accommodate for any requests you receive, and communicate to the event attendee(s) f you can't do so. At the event, we recommend that any food provided is marked with common allergens such as dairy or nuts. More tips on dietary accommodations can be found on <a href="https://drive.google.com/file/d/1v7DlDSdo5lXFurDb9k3YyNJWwA5xfi6v/view" target="_blank">this document</a> on inclusive event planning, prepared by the Social Equity and Diversity Education Office.</p>
`;

copy[32] = `
<p><strong>Why?</strong> One of the largest sources of waste at any event is the dishware that attendees use to eat and drink. This can easily be eliminated by providing preferably reusable dishware, and if this is not logistically possible, then recyclable dishware.</p>
<p><strong>How?</strong> Firstly, if you are working with a caterer or hosting your event at a location that is going to be providing and serving the food, ensure that they will be doing so with reusable, recyclable, or compostable dishware, and that there are appropriate disposal receptacles for attendees. Secondly, sometimes a simple behavior shift can help eliminate dishware waste – for example, instead of having individual disposable cups at a large water filling station, provide pitchers of water with reusable cups in various locations throughout your event. Finally, if you are going to be supplying the dishware for your event, consider contacting <a href="https://theplateclub.wixsite.com/mcgill" target="_blank">The Plate Club</a> – a McGill organization that can provide all types of dishware for your event for free.</p>
`;

copy[33] = `
<p><strong>Why?</strong> Similar to dishware, food packaging can be one of the largest sources of waste for any event. By reducing food packaging waste, you are significantly reducing your event&#39;s ecological footprint, while also providing a generally cleaner environment for event attendees.</p>
<p><strong>How?</strong> Reducing food packaging waste starts at the supplier – ensure that you are purchasing food from suppliers who limit their food packaging, and avoid buying anything that is individually packaged. In addition, many suppliers offer you the ability to bring your own containers when purchasing food, which may be possible depending on the amount of food purchased.</p>
`;

copy[34] = `
<p><strong>Why?</strong> As consumers, we have the ability to affect change with our choices of what to buy. That&#39;s why McGill is a <a href="https://www.mcgill.ca/foodservices/sustainability/fair-trade" target="_blank">Fair-Trade Campus</a>. When choosing to buy fair-trade goods, we can ensure that local farmers and producers receive a stable income in order to support them and their family, as well as enough to invest back into farming methods, clean water and improved community health. As for choosing to purchase organic foods, there are a number of benefits, including healthier food from less pesticide use, ensuring that waterways near agriculture are kept clean, and minimizing fossil fuel use. Events have to purchase food on a large scale, so by selecting organic and/or fair-trade options, you can show businesses that you care about where your products come from and how they are made.</p>
<p><strong>How?</strong> To find fair-trade companies or products, you can search for them on a number of websites <a href="http://www.fairtradefederation.org/find-a-wholesaler-supplier/" target="_blank">here</a>, <a href="http://wfto.com/find-supplier" target="_blank">here</a>, and <a href="http://cftn.ca/products-companies" target="_blank">here</a> for Canadian fair-trade items. Alternatively, you can look for <a href="http://www.fairtradefundraisers.ca/uploads/files/fair_trade_certified.jpg" target="_blank">these</a> symbols when shopping at any grocery store or market. Within Canada, any product that has been certified as being 95% organic or more will have <a href="http://www.caeq.ca/sites/documents/image/LogoBioCanadaRGBpresse.jpg" target="_blank">this</a> logo on it. If it is made with between 70% - 95% organic ingredients, then the percentage will be displayed on the logo as well.</p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">SPF Tiny Stream</a>.</p>
`;

copy[35] = `
<p><strong>Why?</strong> We recognize that when providing food for a large amount of people, there will often be leftovers. Because of this, it is all the more important to ensure that you plan ahead to accommodate for the potential surplus of food. Not only will you be reducing the amount of waste that your event generates, but you might be able to help a worthy cause while doing it.</p>
<p><strong>How?</strong> There are two main ways to plan for excess food: donation or composting. In order to compost, contact <a href="http://www.compostmontreal.com/special-events.html" target="_blank">Compost Montreal</a> well in advance of your event in order to acquire a quote for their services. Compost Montreal is able to provide your event with compostable dishware, cups, and cutlery, as well as with waste receptacles and a personalized on-site service to highlight the steps your event is taking to become more sustainable. The second option is to arrange to have your extra food donated after the event. Contact <a href="https://www.facebook.com/mealcare/" target="_blank">MealCare</a>, a McGill start-up focused on bridging the gap between food waste and food security, in order to learn about whether your surplus food can be donated and how to arrange that. Of course, one of the easiest ways to minimize food surplus/waste is to purchase an appropriate amount! Make sure to strongly consider the nature of your event (timing, length, attendance, etc.) before deciding how much food to purchase and provide.</p>
`;

copy[36] = `
<p><strong>Why?</strong> During longer events (full-day events) it is important to provide food and beverages that have a <a href="https://www.canada.ca/en/health-canada/services/canada-food-guides.html" target="_blank">complete nutrition profile</a>. Providing a balanced menu helps to ensure event attendees are more aware and present during your event.</p>
<p><strong>How?</strong> Consult the <a href="https://www.canada.ca/en/health-canada/services/canada-food-guides.html" target="_blank">Canadian Food Guide</a> in order to learn what types of food can create a nutritionally complete menu.</p>
`;

copy[37] = `
<p><strong>Why?</strong> Providing properly marked waste receptacles is the first step to reducing waste produced from your event. A number of locations where events are held only provide you with a garbage receptacle, and with a lack of other waste receptacles, event attendees have nowhere else to place recycling or compost. By providing them with the option, and clearly communicating the existence and location of these receptacles, you are ensuring that any waste from your event is disposed of properly.</p>
<p><strong>How?</strong> Firstly, it&#39;s important to ensure that you are providing the proper receptacles – there are of course the standard three: garbage, recycling and compost, but we also recommend that you provide a reuse receptacle for any items that could be used again after the event, or later on in the event itself. In addition, it&#39;s important that these receptacles are <a href="https://www.mcgill.ca/sustainability/sustainability-strategy/operations/waste-and-recycling/recycling" target="_blank">clearly marked</a>, in order to avoid any confusion. Finally, ensure that you communicate where these receptacles are located at appropriate times throughout your event. If your event&#39;s location is not able to provide you with compost receptacles, you can acquire them either from <a href="https://theplateclub.wixsite.com/mcgill" target="_blank">The Plate Club</a> or from <a href="http://www.compostmontreal.com/special-events.html" target="_blank">Compost Montreal</a>.</p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">SPF Tiny Stream</a>.</p>
`;

copy[38] = `
<p><strong>Why?</strong> It&#39;s not only your event attendees that can create waste at the event, any material that you distribute during your event can also become waste eventually. With this in mind, it&#39;s important to consider the necessity of any event materials that you distribute, all the way from banners and signs, right down to notepads, pens, and nametags.</p>
<p><strong>How?</strong> Reducing event material comes down to deciding whether it will be necessary for your event or not. Perhaps some materials, such as event agendas or pamphlets, can be published online to reduce printing? If this isn&#39;t possible, consider choosing branded materials that can be reused/recycled/composted, or perhaps reduce redundancy by having attendees share materials. Finally, if you must produce branded materials for your event, ensure that they can be reused, recycled, and/or composted.</p>
`;

copy[39] = `
<p><strong>Why?</strong> Providing the proper waste receptacles is just the first step to reducing waste produced from your event, the next step is to ensure that your event attendees know exactly what should go in each receptacle.</p>
<p><strong>How?</strong> Fortunately, McGill actually has a team of students who are trained in waste management and whose role is to help students learn what goes in each receptacle during the first three weeks of school. They can be contacted at <a href="mailto:sustainability.shhs@mcgill.ca" target="_blank">sustainability.shhs@mcgill.ca</a> in order to request that they attend your event.</p>
<p>In order to finance these potentially additional costs, consider applying to the <a href="https://www.mcgill.ca/sustainability/spf/apply-spf/submit-application-tiny-stream" target="_blank">.</p>
`;

copy[40] = `
<p><strong>Why?</strong> As a whole, McGill uses over 75 million sheets of paper annually, which costs the university $540 thousand (based on 2004 numbers). Considering the environmental impact from this massive amount of paper use – including deforestation, fossil fuel emissions, water pollution, and land filling – any reduction in paper use at the university will have a positive environmental effect.</p>
<p><strong>How?</strong> If you are using paper from the university, or printing it at the university, then you are guaranteed to be abiding by the McGill Paper Policy standards. However, if you are purchasing or printing from a third party, you can look for the following things in order to reduce your footprint:</p>
<ul>
<li>Purchasing paper with greater recycled and post-consumer content, when economically feasible;</li>
<li>Printing and copying double-sided;</li>
<li>Provide as much documentation as possible online in order to reduce unnecessary printing</li>
</ul>
`;

copy[41] = `
<p><strong>Why?</strong> The individual actions you take to make your event more sustainable are incredibly important, but in order to affect change on a larger scale a culture shift is required. Publicizing the sustainability of your event is important in order to accomplish this, as it shows to event attendees that sustainability is an important issue. For some actions, it may even help educate event attendees about changes they can make in their daily habits to live more sustainably.</p>
<p><strong>How?</strong> We recommend ensuring that you communicate the specific actions that your event is taking to make it more sustainable at least three times: once before, during, and after the event. Once your certification score is available, you can also use this as a tool to publicize the sustainability of your event, and we&#39;ll make sure to provide you with appropriate materials to publicize your achievements.</p>
`;

copy[42] = `
<p><strong>Why?</strong> In order to continually improve the services your event offers, it is important to request feedback from event attendees. This feedback is key to informing future event design, and can also help you gauge how successful you were in your various sustainability related actions.</p>
<p><strong>How?</strong> A feedback form can be provided to your event attendees either in person at the event or afterwards via email or another form of online communication. If you are gathering feedback at the event, we recommend trying to do so electronically either with tablets or laptops in order to continue to cut down on paper use. On your feedback form, you may ask questions related to people&#39;s perceptions of the event&#39;s sustainability, whether that increased their enjoyment of the event or detracted from it, and perhaps what suggestions they may have for ensuring your event is even more sustainable next time it&#39;s offered.</p>
`;

copy[43] = `
<p><strong>Why?</strong> During longer events (full-day events) it is important to provide food and beverages that have a <a href="https://www.canada.ca/en/health-canada/services/canada-food-guides.html" target="_blank">complete nutrition profile</a>. Providing a balanced menu helps to ensure event attendees are more aware and present during your event.</p>
<p><strong>How?</strong> Consult the <a href="https://www.canada.ca/en/health-canada/services/canada-food-guides.html" target="_blank">Canadian Food Guide</a> in order to learn what types of food can create a nutritionally complete menu.</p>
`;

copy[44] = `
<p><strong>Why?</strong> In order to continually improve our events at McGill, we must learn from any and all mistakes that are made. By disclosing mistakes related to sustainability, future event-planners can learn from your event and improve upon your work.</p>
<p><strong>How?</strong> When communicating successes after your event, include a section about failures. These can be related to sustainability, but can also be about anything in your event in order to help future event-planners.</p>
`;

copy[45] = `
<p><strong>Why?</strong> Providing documentation and communications in as many languages as is appropriate for your event-attendees helps to make it more accessible for a wider audience.</p>
<p><strong>How?</strong> There is a <a href="https://www.mcgill.ca/translation/home-page-2" target="_blank">McGill Translation Services Office</a> but they unfortunately cannot accommodate for every request. If you have a large document that needs translating, consider reaching out to them, or other external translation services in Montreal such as <a href="http://www.textualis.com" target="_blank">Textualis</a>. For shorter documentation, if somebody on your event-planning team is comfortable translating this is also a great alternative.</p>
`;

copy[46] = `
<p><strong>Why?</strong> By encouraging event attendees and presenters to contribute to the sustainability of the event, you can help create a culture-shift amongst the McGill community.</p>
<p><strong>How?</strong> When communicating the actions that you are taking to make your event more sustainable, you can include ways for event attendees to help. For example, when sending event documentation, include a disclaimer to encourage attendees not to print unnecessary materials.</p>
`;

copy[47] = `
<p><strong>Why?</strong> For longer events (full-day events), especially those focused on sensitive topics, or with a lot of physical or mental stimulation, it is important to provide a space where attendees can take a break if they feel it&#39;s necessary for their physical or mental well being.</p>
<p><strong>How?</strong> Simply provide a space away from the main event area, possibly near food, beverages and/or the restrooms. Ensure that the location of this space is communicated clearly at the beginning and throughout the event.</p>
`;

copy[48] = `
<p><strong>Why?</strong> Single-use water bottles are one of the largest contributors to plastic waste on campus – every year we use more than 100,000 water bottles only to throw them out right afterwards. While recycling them is a step in the right direction, using reusable water bottles completely negates the need for that waste, as well as negates the energy that would have otherwise been used to fill and ship those bottles. This is why McGill has made a huge step by officially banning the sale of single-use water bottles on campus as of May 2019 and taking steps to reduce having single-use water bottles at events.</p>
<p><strong>How?</strong> There are a number of ways to ensure that your event doesn’t need single-use water bottles. Firstly, and perhaps most simply, asking your attendees to bring their own water bottle is always an option. However, if the scale or style of your event does not allow for this, then other options include having water jugs and compostable cups, or water-refill stations and reusable water bottles available at your event.</p>
`;

copy[49] = `
<p><strong>Why?</strong> Providing non-alcoholic options when your event is serving alcohol is incredibly important for providing a safer and more comfortable environment for those who choose not to consume alcohol.</p>
<p><strong>How?</strong> If alcohol is being served, ensure that a non-alcoholic alternative is offered in similar dishware to the alcoholic beverages in order to ensure that people feel comfortable choosing either. Make sure to communicate the different beverage options to your attendees as well. <a href="https://drive.google.com/file/d/1v7DlDSdo5lXFurDb9k3YyNJWwA5xfi6v/view" target="_blank">This resource</a> on inclusive event planning provides useful tips regarding alcoholic beverages at events.</p>
`;

export default copy;
